# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      yml_variable: Tester

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest src/tests/client-test.py
        
    - name: yml variable
      run: |
        echo "yml variable value: $yml_variable" 
    - name: repo variable
      run: |
        echo "repo variable value: ${{ env.SECRET_KEY }}"
    - name: repo secret
      run: |
        echo "repo secret value: ${{ secrets.SECRET_KEY }}" 
    # - name: custom dev variable
    #  run: |
    #    echo "custom dev variable value: ${{ dev.ENV_VAR }}" 
    # - name: custom dev secret
    #  run: |
    #    echo "custom dev secret value: ${{ dev.secrets.ENV_VAR }}"
        
